=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/production.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dei.isep.ipp.pt/tap-2021" xmlns:tns="http://www.dei.isep.ipp.pt/tap-2021" elementFormDefault="qualified">
	<include schemaLocation="scheduleSimple.xsd"/>

    <element name="Production" type="tns:TProduction"></element>

    <complexType name="TProduction">
    	<sequence>
    		<element name="PhysicalResources">
    			<complexType>
    				<sequence>
    					<element name="Physical" type="tns:TPhysical" maxOccurs="unbounded"/>
    				</sequence>
    			</complexType>
    		</element>
    		<element name="Tasks">
    			<complexType>
    				<sequence>
    					<element name="Task" type="tns:TTask" maxOccurs="unbounded"/>
    				</sequence>    				    				
    			</complexType>    			
    		</element>
    		<element name="HumanResources">
    			<complexType>
    				<sequence>
    					<element name="Human" type="tns:THuman" maxOccurs="unbounded"/>
    				</sequence>
    			</complexType>
    		</element>    		    	    		
    		<element name="Products">
    			<complexType>
    				<sequence>
    					<element name="Product" type="tns:TProduct" maxOccurs="unbounded"/>
    				</sequence>
    			</complexType>
    		</element>    		
    		<element name="Orders">
    			<complexType>
    				<sequence>
    					<element name="Order" type="tns:TOrder" maxOccurs="unbounded"/>
    				</sequence>
    			</complexType>
    		</element>    		
    	</sequence>
    </complexType>

	<complexType name="TPhysical">
    	<attribute name="id" type="tns:STPhysicalId" use="required"/>
    	<attribute name="type" type="string"/>
    </complexType> 
	<complexType name="TTask">
    	<sequence>
    		<element name="PhysicalResource" maxOccurs="unbounded">
	    		<complexType>
	    			<attribute name="type" type="string" use="required"/>
	    		</complexType>
	    	</element>
    	</sequence>
    	<attribute name="id" type="tns:STTaskId" use="required"/>
		<attribute name="time" type="positiveInteger" use="required"/>    	
    </complexType>    
	<complexType name="THuman">
		<sequence>
    		<element name="Handles" maxOccurs="unbounded">
    			<complexType>
					<attribute name="type" type="string" use="required"/>
    			</complexType>
    		</element>    		
    	</sequence>	
    	<attribute name="id" type="tns:STHumanId" use="required"/>
    	<attribute name="name" type="string"/>
    </complexType>    
    <complexType name="TProduct">
    	<sequence>
    		<element name="Process" maxOccurs="unbounded">
    			<complexType>
					<attribute name="tskref" type="tns:STTaskIdRef" use="required"/>
    			</complexType>
    		</element>    		
    	</sequence>
		<attribute name="id" type="tns:STProductId" use="required"/>
    	<attribute name="name" type="string"/>    	
    </complexType>
	<complexType name="TOrder">
    	<attribute name="id" type="tns:STOrderId" use="required"/>
    	<attribute name="prdref" type="tns:STProductIdRef" use="required"/>
    	<attribute name="quantity" type="positiveInteger" use="required"/>
    </complexType>     
</schema>

=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/assessment/ms03/validAgenda70_in.xml
<?xml version='1.0' encoding="UTF-8"?>
<Production 
xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2021 ../../production.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dei.isep.ipp.pt/tap-2021">
    <PhysicalResources>
        <Physical id="PRS_01" type="PRST_2"/>
        <Physical id="PRS_02" type="PRST_1"/>
        <Physical id="PRS_03" type="PRST_3"/>
        <Physical id="PRS_04" type="PRST_7"/>
        <Physical id="PRS_05" type="PRST_4"/>
        <Physical id="PRS_06" type="PRST_7"/>
        <Physical id="PRS_07" type="PRST_2"/>
        <Physical id="PRS_08" type="PRST_4"/>
        <Physical id="PRS_09" type="PRST_2"/>
        <Physical id="PRS_10" type="PRST_5"/>
        <Physical id="PRS_11" type="PRST_5"/>
        <Physical id="PRS_12" type="PRST_1"/>
        <Physical id="PRS_13" type="PRST_1"/>
        <Physical id="PRS_14" type="PRST_4"/>
        <Physical id="PRS_15" type="PRST_6"/>
        <Physical id="PRS_16" type="PRST_3"/>
        <Physical id="PRS_17" type="PRST_7"/>
        <Physical id="PRS_18" type="PRST_1"/>
        <Physical id="PRS_19" type="PRST_1"/>
        <Physical id="PRS_20" type="PRST_2"/>
    </PhysicalResources>
    <Tasks>
        <Task id="TSK_01" time="9">
            <PhysicalResource type="PRST_2"/>
        </Task>
        <Task id="TSK_02" time="9">
            <PhysicalResource type="PRST_7"/>
        </Task>
    </Tasks>
    <HumanResources>
        <Human id="HRS_01" name="name of 01">
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_6"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_7"/>
        </Human>
        <Human id="HRS_02" name="name of 02">
            <Handles type="PRST_1"/>
        </Human>
        <Human id="HRS_03" name="name of 03">
            <Handles type="PRST_3"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_04" name="name of 04">
            <Handles type="PRST_7"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_6"/>
            <Handles type="PRST_5"/>
        </Human>
        <Human id="HRS_05" name="name of 05">
            <Handles type="PRST_4"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_06" name="name of 06">
            <Handles type="PRST_7"/>
            <Handles type="PRST_3"/>
        </Human>
        <Human id="HRS_07" name="name of 07">
            <Handles type="PRST_2"/>
            <Handles type="PRST_7"/>
        </Human>
        <Human id="HRS_08" name="name of 08">
            <Handles type="PRST_4"/>
            <Handles type="PRST_7"/>
        </Human>
        <Human id="HRS_09" name="name of 09">
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_10" name="name of 10">
            <Handles type="PRST_5"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_11" name="name of 11">
            <Handles type="PRST_5"/>
            <Handles type="PRST_1"/>
        </Human>
        <Human id="HRS_12" name="name of 12">
            <Handles type="PRST_1"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_6"/>
            <Handles type="PRST_5"/>
        </Human>
        <Human id="HRS_13" name="name of 13">
            <Handles type="PRST_1"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_14" name="name of 14">
            <Handles type="PRST_4"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_5"/>
        </Human>
        <Human id="HRS_15" name="name of 15">
            <Handles type="PRST_6"/>
            <Handles type="PRST_1"/>
        </Human>
        <Human id="HRS_16" name="name of 16">
            <Handles type="PRST_3"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_7"/>
        </Human>
        <Human id="HRS_17" name="name of 17">
            <Handles type="PRST_7"/>
            <Handles type="PRST_1"/>
        </Human>
        <Human id="HRS_18" name="name of 18">
            <Handles type="PRST_1"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_19" name="name of 19">
            <Handles type="PRST_1"/>
            <Handles type="PRST_2"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
        <Human id="HRS_20" name="name of 20">
            <Handles type="PRST_2"/>
            <Handles type="PRST_1"/>
            <Handles type="PRST_3"/>
            <Handles type="PRST_7"/>
            <Handles type="PRST_4"/>
            <Handles type="PRST_5"/>
            <Handles type="PRST_6"/>
        </Human>
    </HumanResources>
    <Products>
        <Product id="PRD_01" name="Product 01">
            <Process tskref="TSK_01"/>
            <Process tskref="TSK_02"/>
        </Product>
        <Product id="PRD_02" name="Product 02">
            <Process tskref="TSK_01"/>
        </Product>
        <Product id="PRD_03" name="Product 03">
            <Process tskref="TSK_01"/>
            <Process tskref="TSK_02"/>
        </Product>
        <Product id="PRD_04" name="Product 04">
            <Process tskref="TSK_01"/>
        </Product>
        <Product id="PRD_05" name="Product 05">
            <Process tskref="TSK_01"/>
        </Product>
        <Product id="PRD_06" name="Product 06">
            <Process tskref="TSK_01"/>
            <Process tskref="TSK_02"/>
        </Product>
        <Product id="PRD_07" name="Product 07">
            <Process tskref="TSK_01"/>
        </Product>
        <Product id="PRD_08" name="Product 08">
            <Process tskref="TSK_01"/>
        </Product>
    </Products>
    <Orders>
        <Order id="ORD_01" prdref="PRD_01" quantity="1"/>
        <Order id="ORD_02" prdref="PRD_02" quantity="2"/>
        <Order id="ORD_03" prdref="PRD_03" quantity="5"/>
        <Order id="ORD_04" prdref="PRD_04" quantity="1"/>
        <Order id="ORD_05" prdref="PRD_05" quantity="5"/>
        <Order id="ORD_06" prdref="PRD_06" quantity="2"/>
        <Order id="ORD_07" prdref="PRD_07" quantity="1"/>
        <Order id="ORD_08" prdref="PRD_08" quantity="5"/>
    </Orders>
</Production>

=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/assessment/ms03/testFiles/invalidAgenda_NoEnoughPhysicals_in.xml
<?xml version="1.0" encoding="UTF-8"?>
<Production xmlns="http://www.dei.isep.ipp.pt/tap-2021" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2021 ../../production.xsd ">
  <PhysicalResources>
    <Physical id="PRS_1" type="PRST 1"/>
    <Physical id="PRS_2" type="PRST 1"/>
  </PhysicalResources>
  <Tasks>
    <Task id="TSK_1" time="100">
      <PhysicalResource type="PRST 1"/>
      <PhysicalResource type="PRST 1"/>
      <PhysicalResource type="PRST 1"/>
    </Task>
  </Tasks>    
  <HumanResources>
    <Human id="HRS_1" name="Antonio">
      <Handles type="PRST 1"/>
    </Human>
    <Human id="HRS_2" name="Maria">
      <Handles type="PRST 1"/>
    </Human>
    <Human id="HRS_3" name="Manuel">
      <Handles type="PRST 1"/>
    </Human>
  </HumanResources>
  <Products>
    <Product id="PRD_1" name="Product 1">
      <Process tskref="TSK_1"/>
    </Product>
  </Products>
  <Orders>
  	<Order id="ORD_1" prdref="PRD_1" quantity="1"/>
  </Orders>
</Production>
