=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dei.isep.ipp.pt/tap-2021" xmlns:tns="http://www.dei.isep.ipp.pt/tap-2021" elementFormDefault="qualified">
	<include schemaLocation="scheduleSimple.xsd"/>

    <element name="Schedule" type="tns:TSchedule"></element>

    <complexType name="TSchedule">
    	<sequence>
    		<element name="TaskSchedule" type="tns:TTaskSchedule" maxOccurs="unbounded"/>
    	</sequence>
    </complexType>

	<complexType name="TTaskSchedule">
    	<sequence>
    		<element name="PhysicalResources">
    			<complexType>
    				<sequence>
    					<element name="Physical" maxOccurs="unbounded">
    						<complexType>
    							<attribute name="id" type="string" use="required"/>
    						</complexType>
    					</element>
    				</sequence>
    			</complexType>    		
    		</element>
    		<element name="HumanResources">
    			<complexType>
    				<sequence>
    					<element name="Human" maxOccurs="unbounded">
    						<complexType>
    							<attribute name="name" type="string" use="required"/>
    						</complexType>
    					</element>
    				</sequence>
    			</complexType>    		
    		</element>    		
    	</sequence>	
    	<attribute name="order" type="string" use="required"/>
    	<attribute name="productNumber" type="int" use="required"/>
    	<attribute name="task" type="string" use="required"/>
    	<attribute name="start" type="int" use="required"/>
    	<attribute name="end" type="int" use="required"/>    	
    </complexType>      
</schema>

=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/assessment/ms03/validAgenda57_out.xml
<?xml version='1.0' encoding="UTF-8"?>
<Schedule 
xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2021 ../../schedule.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dei.isep.ipp.pt/tap-2021">
    <TaskSchedule order="ORD_01" productNumber="1" task="TSK_01" start="0" end="6">
        <PhysicalResources>
            <Physical id="PRS_01"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_01" productNumber="2" task="TSK_01" start="0" end="6">
        <PhysicalResources>
            <Physical id="PRS_02"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 02"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_01" productNumber="3" task="TSK_01" start="0" end="6">
        <PhysicalResources>
            <Physical id="PRS_07"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 03"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_01" productNumber="4" task="TSK_01" start="6" end="12">
        <PhysicalResources>
            <Physical id="PRS_01"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_02" productNumber="1" task="TSK_01" start="6" end="12">
        <PhysicalResources>
            <Physical id="PRS_02"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 02"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="1" task="TSK_01" start="6" end="12">
        <PhysicalResources>
            <Physical id="PRS_07"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 03"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_02" productNumber="1" task="TSK_02" start="12" end="22">
        <PhysicalResources>
            <Physical id="PRS_04"/>
            <Physical id="PRS_01"/>
            <Physical id="PRS_03"/>
            <Physical id="PRS_05"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
            <Human name="name of 02"/>
            <Human name="name of 03"/>
            <Human name="name of 04"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="2" task="TSK_01" start="12" end="18">
        <PhysicalResources>
            <Physical id="PRS_02"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 05"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="3" task="TSK_01" start="18" end="24">
        <PhysicalResources>
            <Physical id="PRS_02"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 05"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="1" task="TSK_02" start="22" end="32">
        <PhysicalResources>
            <Physical id="PRS_04"/>
            <Physical id="PRS_01"/>
            <Physical id="PRS_03"/>
            <Physical id="PRS_05"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
            <Human name="name of 02"/>
            <Human name="name of 03"/>
            <Human name="name of 04"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="4" task="TSK_01" start="24" end="30">
        <PhysicalResources>
            <Physical id="PRS_02"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 05"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="2" task="TSK_02" start="32" end="42">
        <PhysicalResources>
            <Physical id="PRS_04"/>
            <Physical id="PRS_01"/>
            <Physical id="PRS_03"/>
            <Physical id="PRS_05"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
            <Human name="name of 02"/>
            <Human name="name of 03"/>
            <Human name="name of 04"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="3" task="TSK_02" start="42" end="52">
        <PhysicalResources>
            <Physical id="PRS_04"/>
            <Physical id="PRS_01"/>
            <Physical id="PRS_03"/>
            <Physical id="PRS_05"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
            <Human name="name of 02"/>
            <Human name="name of 03"/>
            <Human name="name of 04"/>
        </HumanResources>
    </TaskSchedule>
    <TaskSchedule order="ORD_03" productNumber="4" task="TSK_02" start="52" end="62">
        <PhysicalResources>
            <Physical id="PRS_04"/>
            <Physical id="PRS_01"/>
            <Physical id="PRS_03"/>
            <Physical id="PRS_05"/>
        </PhysicalResources>
        <HumanResources>
            <Human name="name of 01"/>
            <Human name="name of 02"/>
            <Human name="name of 03"/>
            <Human name="name of 04"/>
        </HumanResources>
    </TaskSchedule>
</Schedule>

=== Sailor-Saturn/Scala-Project-2021/1160941-tap-2021-g1-m1b-1b87b44697b8 2/files/assessment/ms03/validAgenda_11_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<Schedule xmlns="http://www.dei.isep.ipp.pt/tap-2021" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dei.isep.ipp.pt/tap-2021 ../../schedule.xsd ">
	<TaskSchedule order="ORD_1" productNumber="1" task="TSK_1"
				  start="0" end="5">
		<PhysicalResources>
			<Physical id="PRS_1" />
			<Physical id="PRS_4" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Antonio" />
			<Human name="Maria" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_2" productNumber="1" task="TSK_3"
				  start="0" end="2">
		<PhysicalResources>
			<Physical id="PRS_2" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Joao" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_2" productNumber="1" task="TSK_4"
				  start="2" end="6">
		<PhysicalResources>
			<Physical id="PRS_6" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Joao" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_1" productNumber="1" task="TSK_2"
				  start="5" end="8">
		<PhysicalResources>
			<Physical id="PRS_2" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Antonio" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_1" productNumber="2" task="TSK_1"
				  start="6" end="11">
		<PhysicalResources>
			<Physical id="PRS_1" />
			<Physical id="PRS_4" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Maria" />
			<Human name="Joao" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_2" productNumber="2" task="TSK_3"
				  start="8" end="10">
		<PhysicalResources>
			<Physical id="PRS_2" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Antonio" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_2" productNumber="2" task="TSK_4"
				  start="10" end="14">
		<PhysicalResources>
			<Physical id="PRS_6" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Antonio" />
		</HumanResources>
	</TaskSchedule>
	<TaskSchedule order="ORD_1" productNumber="2" task="TSK_2"
				  start="11" end="14">
		<PhysicalResources>
			<Physical id="PRS_2" />
		</PhysicalResources>
		<HumanResources>
			<Human name="Maria" />
		</HumanResources>
	</TaskSchedule>
</Schedule>
